Module 1: Html and Css Personal Portfolio Website.
alvinlouis29/Portfolio-website pull request #1
Opened 2021-09-16 22:18 UTC by alvinlouis29

##The goal of the project is to understand how to parse a Figma design to create a User Interface of my personal portfolio website.
##I have used flex box to place the elements in the page and also used a background to enhance the look and feel of the site.

2021-09-16 23:07 UTC, ZeenatLawal requested changes
Hi @alvinlouis29, 

Great job so far!:clap: :clap:
## To Highlight 🎊 🎊 
- GitHub flow is followed. ✔️
- PR has a title and summary. ✔️

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Removing the -ed suffix at the end of your commit verbs(e.g. Add instead of added)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-16 23:07 UTC, ZeenatLawal commented on index.html
> +                </div>
- [ ] The main title (Hey there. I'm Alvin) should be an `h1` tag as specified in the requirements.
- [ ] The subtitle (I'm a software developer) should be a `header` tag (examples: `h2`,`h3`,`h4`, etc...)

2021-09-16 23:07 UTC, ZeenatLawal commented on style.css
> +}
- [ ] Kindly make sure you use the same font (Inter) as defined in the template

2021-09-17 00:47 UTC, alvinlouis29 commented on index.html
> +                </div>
I used a span, the header tags don't work when I use them in this scenario, I think It's because these are two different header tags.

2021-09-17 00:47 UTC, alvinlouis29 commented on style.css
> +}
added the font from google fonts

2021-09-17 01:12 UTC, BrianSammit approved these changes
# STATUS: APROVED :green_circle: :clap: 

Hello @alvinlouis29 , 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-17 01:13 UTC, merged