Module 1: Portfolio website Desktop version
alvinlouis29/Portfolio-website pull request #4
Opened 2021-09-24 12:47 UTC by alvinlouis29

##In this milestone of  building my Portfolio Website, I have designed the Desktop Version of this website, parsing the Figma ##Design of this project
![desktop_screenshot](https://user-images.githubusercontent.com/46988029/134676252-09fa8d52-7bdd-4e93-8d88-6a14d7d70a9a.png)
.

2021-09-24 13:50 UTC, uwadonat requested changes
Hi **@alvinlouis29**, 

Good job so far! :mechanical_arm: implementing most of the requirements for this project.

### To highlight! :+1: 
- Your pull request message is very descriptive ✔️
- You are using HTML/CSS best practice ✔️

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Let's focus on the mobile-first approach. On desktop version the value for min-width property should be in range of 992px - 1100px

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-24 23:48 UTC, Mihndim2020 requested changes
## Hi @alvinlouis29 , 

Great work on making the changes requested by a previous reviewer 👏 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![stay-strong-youre-almost-there](https://user-images.githubusercontent.com/65852621/133678845-1b015b27-e9bc-4784-a316-bc699db8237a.jpg)


 # Status: Requires Changes ♻️
_Check the comments under the review._

Please do consider, as requested by the previews reviewer:
- [ ] As requested by the  previous code reviewer, which is also part of the project requirements and best practice, make you define your media queries breakpoint for the Desktop in the CSS file (the value for min-width property should be in range of 992px - 1100px). There no need defining media queries for the mobile version, since we are using the mobile first approach. Please kindly fix that.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-25 05:09 UTC, jmontanholi requested changes
Hello Alvin Louis Ssegawa!

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I working on optional suggestions is always good, with them you may learn something new or make your project look more professional._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

![](https://media0.giphy.com/media/VdW96O9QVNXkkharuG/giphy.gif)

2021-09-25 05:09 UTC, jmontanholi commented on style.css
> +@media only screen and (min-width: 769px) {
- [ ] Your media should have a min-width value of something between 992 and 1100 pixels, this way it will be for desktops, on 769 it is closer to Ipads. Please consider changing it.

2021-09-29 14:09 UTC, closed without merging